version: "3"
services:
  db:
    container_name: beatstar
    image: postgres
    ports:
      - $PGPORT:$PGPORT
    environment:
      POSTGRES_DB: $PGDATABASE
      POSTGRES_USER: $PGUSER
      POSTGRES_PASSWORD: $PGPASSWORD
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  db-data:
